### ISSUE TITLE
GitHub workflows fail

### ISSUE THREAD

**Issue by teofiln** [teofiln/utilhisse#6]
Due to bioconductor dependencies..

@novica how do we tell the workflow about bioconductor?

**Comment by novica** [comment]
Relevant: https://lcolladotor.github.io/biocthis/articles/biocthis.html#use-bioc-github-action-

 R-CMD-check-bioc  seems to work. --- i.e. fails because of non bioc issue :+1: 
checking package dependencies ... ERROR
  Package required but not available: ‘colorplaner’
  
  See section ‘The DESCRIPTION file’ in the ‘Writing R Extensions’
  manual.

Test coverage and pkgdown fail because of the bioc dependencies.
